### ISSUE TITLE
Author Extra Info dilemma

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#100]
A. Under the "author extra info" in the main layout page, when we want to edit, we cannot change that. It is not under "edit". 

You can fix that by going to "Navigate" and then "Author" and then "Edit", but it is a long process.   

B. We also notice that under "Edit" we do not find the Author name in original language, or extra information etc. It appears in layout but not under "Edit". The same applies to "Translator" info.  

If you need a video or meeting to explain what we mean, let us know

![image](https://user-images.githubusercontent.com/61408472/102334165-a456f400-3f8e-11eb-8fdb-6dbcbc9088f0.png)

**Comment by Woseseltops** [comment]
I propose instead of the select2 field (the field where you can add grey boxes):

![image](https://user-images.githubusercontent.com/1909317/102470997-efd3d580-4054-11eb-8ca0-d7ead5af6e86.png)

You get something like this:

```
* Fr. Luka El Antony | القمص لوقا الأنطونى (extra info)    [edit] [delete]
* Father Menassa Youhanna | القس منسى يوحنا (extra info)     [edit] [delete]
```

If you the edit button you can edit on the fly (@Mergpijp : in a modal). This is really similar to the redesign of UploadedFile @Mergpijp is currently working on in #62 and #90, so by the time he gets to this issue he will be an expert on this :).

**Comment by Mergpijp** [comment]
Yes working on it. I did not yet made the edit/update modal hope it works.

**Comment by Elisagig** [comment]
Succes! Thanks

**Comment by Woseseltops** [comment]
Almost working, last thing to do: clear lists of search results after searching.

**Comment by Woseseltops** [comment]
@Mergpijp is stuck here, to investigate later.

**Comment by Woseseltops** [comment]
If I'm not mistaken, this is also related to Habtom's desire to edit authors in a modal. Right now, the edit button is not always there.

**Comment by Elisagig** [comment]
Yes. True

**Comment by Elisagig** [comment]
Asked by colleagues on 25 Feb: 
 
Author can be created (and found in ‘Authors’) but not shown in the overview and publication details. Also not searchable in the main ‘Search’ tab.

**Comment by Mergpijp** [comment]
Yes this issue was noted by Habtom on slack. It should be solved with the new deployment on 26 february
