### ISSUE TITLE
Multiplication of pages and other urgent problems

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#108]
Heleen and some colleagues contacted me yesterday saying there is an urgent problem in the database and that there is a multiplication of pages. They are saying the site is not functioning well. Kindly check @Mergpijp @Woseseltops 

![image](https://user-images.githubusercontent.com/61408472/106862886-05b25e00-66c8-11eb-8f26-02b31523cadc.png)

**Comment by Woseseltops** [comment]
I can confirm by going through the list indeed. Possibly related findings: 
* all the creation dates are Feb 1
* something seems off for the pictures as well: I see the same titles multiple times, but with different pictures (but the pictures are ).

From what I can see, this is only a problem with the website, not with the underlying data. However, if I am mistaken and the problem IS the underlying data, we do have a functioning backup system (see #98 ).

@Elisagig , @Mergpijp will be available Friday afternoon again.... would it be okay if we fix it then, or is this more urgent for you (so we need to contact @Mergpijp earlier).

**Comment by Mergpijp** [comment]
So this is recent possibly due to changes that I made. I have a hunch its due to the double for loop one for publications and one for cover images. I can quickly fix this if neede

**Comment by Elisagig** [comment]
Sorry replying now. I am off on Wednesdays and Thursdays so I only sent that email and slack message because my colleagues contacted me saying it is urgent and asking me to send an email ASAP. Unfortunately I was in my other work and did not notice your answers except for now. So I assume we will work on it today

**Comment by Woseseltops** [comment]
No problem @Elisagig !

**Comment by Mergpijp** [comment]
Sorry for creating this problem. It was unnecessary and clumsy of me.

**Comment by Woseseltops** [comment]
Please reopen if this shows up again.
