### ISSUE TITLE
Make stubs is_deleted true to put in thrash bin for later recovery

### ISSUE THREAD

**Issue by Mergpijp** [Mergpijp/GlobalOrthodoxy#138]
Something goes wrong when copying from stub to another publication. We want to lose zero data when they are entered hence this issue.

**Comment by Woseseltops** [comment]
I just, totally by accident, discovered that Github has the same 'stub' functionality: when creating a new issue I can link it to a milestone before I click submit. Interestingly, they seem to link a stub to a user: if I start a new issue, leave the page before clicking submit, and then click 'create issue' again, I 'recover' the information that was there before I left the page (that is, the stub) instead of a normal empty 'create issue' page.

**Comment by Mergpijp** [comment]
Interesting

**Comment by Woseseltops** [comment]
Put my idea in #148 .
