### ISSUE TITLE
Modals to edit authors, translators and uploaded files, directly from a publication

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#153]
In #145 we solved this with a workaround (open a separate tab). In this issue we want to solve it the right way.

**Comment by Elisagig** [comment]
Got some issues related to this from my colleague Habtom: 
He says that in some books we cannot see any author but we do see translators. Yet when we go to "Titles" then "Author Name" we can't see the translator. This applies to a book called "Timhrte Negere Melekot" for example.  The issue was reported yesterday.

**Comment by Elisagig** [comment]
My colleagues are saying that the issue with editing authors, translators and files is still not fixed. Now it doesn't even open a new window for my colleagues. They say it starts loading and disappears in a second.

**Comment by Woseseltops** [comment]
Hey @Elisagig will create a separate issue for this!

**Comment by Woseseltops** [comment]
@Mergpijp showed me this works now, finally after all these hours! Congratulations. Will be available at next deploy.
