### ISSUE TITLE
You shouldn't be able to link general concepts to publications

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#68]
At the moment it is possible to link general concepts, like a new church, city or language, to a publication as well, while this linking to publications should only be available for uploaded files.

**Comment by Mergpijp** [comment]
I do not really get what you mean here. Do you mean when getting the popup of a church that you can add publications there? And that that should be removed?

**Comment by Woseseltops** [comment]
I'll explain it with an example. Say I'm adding a new publication in Zulu, but Zulu is not in the list of languages. I decide to add it, so it can be selected in the future. The popup shows me this:

![image](https://user-images.githubusercontent.com/1909317/92248291-bb367680-eec8-11ea-9b57-3212b96c6e71.png)

Why is the publications field there? I just want to add a new language (general concept), not a language for 1 specific publication.

**Comment by Mergpijp** [comment]
In another issue you told me to rename 'publications' to 'publication' and now you want me to delete all fields from a general concept?

**Comment by Woseseltops** [comment]
Correct... the only place where the 'publication' field stays is UploadedFile, als this is not a general concept.

**Comment by Elisagig** [comment]
Message from my colleague Matija: 
"Regarding Linking an image to the right publication - if you are on the 'Create page', uploading a new publication and you are adding a new file (image), you cannot link it to the current publication that you are working on - it is not on the list since it has not been saved yet. We don't want to go the other way around and link the image through navigate --> uploaded files --> edit and then link it to the desired publication (also, at least search option would be helpful here since the list is getting pretty long). That is time consuming and sometimes it doesn't even work, as some of us experienced it. So it would be good if while being on the Create page - uploading a new publication and then a file, that it links automatically on the spot (that is another thing that worked only occasionally, as we could see during the meeting as well)".

**Comment by Elisagig** [comment]
Uploading images, some problems.  One problem relates to Image linking to publication. Wrong linking between images. We have to check if it is from the former problem. We can't always link to the right publication.
