### ISSUE TITLE
Backup files regularly

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#98]
Kindly backup files regularly (weekly) to avoid losing the work.

**Comment by Woseseltops** [comment]
Will take this up next Thursday.

**Comment by Woseseltops** [comment]
Configured it like this: every day, a copy of the data is saved to another location. Because this would mean that after two years we would have 730 backups, the backup folder is cleaned so that for backups only than 2 week, we keep only 1 per week, for backup older than 1 month, we keep only 1 per month, and for backups older than 6 months, we keep only 2 per year.

This prevents against (ordered by likeliness):
* Developer mistakes: Emmanuel by accident deletes all data
* Data corruption: there is a bug in the database that slowly ruins the data without us noticing (even if it takes months before we notice)
* User mistakes: users by accident delete a lot of important stuff that is hard to rebuild (even it takes months before s/he notices).
* Disk failure: the place where the data is stored is broken somehow

This does not prevent against:
* The whole server room catching fire or exploding or something like that; the data is still in that same physical room.

===
Please leave this issue open for some time so I remember to check every now and then if things are working as intended.

**Comment by Mergpijp** [comment]
Thought I did backup the database but it was a dummy file in the repo. The real database is in the writable folder. Made a backup today (manually) to have one.

**Comment by Mergpijp** [comment]
Better to leave this issue open because the automatic backup functionality is not yet made.

**Comment by Mergpijp** [comment]
Come to think of it the databse is backed up but the images are not. @Woseseltops Is it important to backup images?

**Comment by Woseseltops** [comment]
Some miscommunication here: I configured the backups already, you can find them in /vol/archive/backups . Images are backed up as well.
